In [1]:
import numpy as np

In [2]:
from Hermes import Hermes
myHermes = Hermes()
myHermes.addFilter('cone_search')
myHermes.addFilter('ra', '12:26:27.011') # SN 2021J
myHermes.addFilter('dec','+31:13:20.55')
myHermes.addFilter('radius', 10.0)

In [3]:
myHermesBox = Hermes()
myHermesBox.addFilter('box_search')
myHermesBox.addFilter('ra', '12:26:27.011') # SN 2021J
myHermesBox.addFilter('dec','+31:13:20.55')
myHermesBox.addFilter('height', 10.0)
myHermesBox.addFilter('width', 10.0)

In [4]:
#myHermes.addFilter('cone_searcha')


In [4]:
myHermes.getFilters()


{'search_type': {'type': 'cone_search', 'radius': 10.0},
 'ra/dec': ['12:26:27.011', '+31:13:20.55']}

In [5]:
my_query = myHermes.startQuery()
print(len(my_query))
print(my_query.keys())

for query in my_query:
    print('-------------------------------------------------------------------\n')
    print(my_query[query])

{'MAST': <Services.MAST.QueryMAST object at 0x7ff0d22ba5b0>}
MAST
Start query MAST
query  timeseries
INFO: Found cached file ./mastDownload/HLSP/hlsp_qlp_tess_ffi_s0022-0000000082346904_tess_v01_llc/hlsp_qlp_tess_ffi_s0022-0000000082346904_tess_v01_llc.fits with expected size 80640. [astroquery.query]
INFO: Found cached file ./mastDownload/HLSP/hlsp_qlp_tess_ffi_s0022-0000000082346904_tess_v01_llc/hlsp_qlp_tess_ffi_s0022-0000000082346904_tess_v01_llc.txt with expected size 54085. [astroquery.query]
INFO: Found cached file ./mastDownload/HLSP/hlsp_qlp_tess_ffi_s0022-0000000082346910_tess_v01_llc/hlsp_qlp_tess_ffi_s0022-0000000082346910_tess_v01_llc.fits with expected size 80640. [astroquery.query]
INFO: Found cached file ./mastDownload/HLSP/hlsp_qlp_tess_ffi_s0022-0000000082346910_tess_v01_llc/hlsp_qlp_tess_ffi_s0022-0000000082346910_tess_v01_llc.txt with expected size 54672. [astroquery.query]
INFO: Found cached file ./mastDownload/HLSP/hlsp_qlp_tess_ffi_s0022-0000000082346919_tess_v01

[(9.4998026e-01, -797.73505, 77.46869 , 545.2913 , -306.99838, -1.2418566e-03, 0.00204117, 0.00854471, -7.77881010e-04, 0.00239887, 0.00966039, 186.6127238 , 31.22344622, 350.06372565,  63.715096, 9.06515198e+01, 49.615116 , 26.27069 ,  80.89103 , -5.76000847e-02, 0.30239996, 0.17759994, 35.799995, 1.6e+38, 1, 0, 1, 0)
 (3.9499803e+00, -797.7337 , 77.46876 , 545.2932 , -306.99713,  3.7571401e-04, 0.00192068, 0.01043674, -1.12921778e-04, 0.00277279, 0.01524698, 186.61272332, 31.22344596, 350.06372656,  64.382454, 9.06515121e+01, 49.615154 , 26.270668,  80.891075, -5.76000400e-02, 0.3066397 , 0.17472   , 35.800022, 1.6e+38, 1, 0, 1, 0)
 (6.9499803e+00, -797.73444, 77.46882 , 545.2921 , -306.99622, -5.2363379e-04, 0.0033107 , 0.01721302,  3.78060795e-04, 0.00246647, 0.01341778, 186.61272363, 31.22344587, 350.06372562,  64.45797 , 9.17955399e+01, 48.984825 , 26.394112,  81.54631 , -6.19200915e-02, 0.30295992, 0.17280003, 35.800022, 1.6e+38, 1, 0, 1, 0)
 (9.9499807e+00, -797.73474, 77.4697 

[[1515 1517 1517 ... 1504 1512 1498]
 [1512 1513 1514 ... 1504 1508 1496]
 [1511 1516 1514 ... 1507 1511 1501]
 ...
 [1510 1514 1514 ... 1501 1511 1497]
 [1516 1513 1514 ... 1503 1510 1496]
 [1521 1514 1514 ... 1505 1507 1495]]
[-21846 -21846 -21846 -21846 -21846 -21846 -21846 -21846  13875  19968
  12344  20020   1032   5448     16  -4419   1150 -23676  18104      0
   1755 -19051    841      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0      0      3   1044   1062    501    519      0      0      0
      0      0      0      0      0      0      0      0      0      0
      0     34    115      0 -22704 -16528 -16416 -15008 -14944 -15488
 -15344  -7824 -12928 -12912 -19792 -17392 -17584 -20272 -11440 -19728
 -21568 -15856   7984  -8080 -16640 -11856 -13296 -13328 -1334

{'timeseries': [{'header': XTENSION= 'BINTABLE'           / binary table extension                         
BITPIX  =                    8 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                   56 / length of dimension 1                          
NAXIS2  =                 1248 / length of dimension 2                          
PCOUNT  =                    0 / number of group parameters                     
GCOUNT  =                    1 / number of groups                               
TFIELDS =                   13 / number of table fields                         
TTYPE1  = 'TIME    '                                                            
TFORM1  = 'D       '                                                            
TUNIT1  = 'BJD-2457000, days'                                                   
TTYPE2  = 'CADENCENO'                                                           
T

In [36]:
print(len(my_query['MAST']['timeseries']))

table = 0 # 0, 1, 2, 3
print(my_query['MAST']['timeseries'][table]['data'].columns)
print(my_query['MAST']['timeseries'][table]['data'][0])

4
ColDefs(
    name = 'TIME'; format = 'D'; unit = 'BJD-2457000, days'
    name = 'CADENCENO'; format = 'J'
    name = 'SAP_FLUX'; format = 'E'
    name = 'KSPSAP_FLUX'; format = 'E'
    name = 'KSPSAP_FLUX_ERR'; format = 'E'
    name = 'QUALITY'; format = 'J'
    name = 'ORBITID'; format = 'J'
    name = 'SAP_X'; format = 'E'; unit = 'pixel'
    name = 'SAP_Y'; format = 'E'; unit = 'pixel'
    name = 'SAP_BKG'; format = 'E'
    name = 'SAP_BKG_ERR'; format = 'E'
    name = 'KSPSAP_FLUX_SML'; format = 'E'
    name = 'KSPSAP_FLUX_LAG'; format = 'E'
)
(1899.327856474589, 32249, 1.0460593, 1.0101, 0.005967969, 4096, 51, 1223.6448, 235.56285, -4303.61, 1030.81, 1.0367149, 1.0108598)


In [38]:
print(len(my_query['MAST']['spectrum']))

table = 0 # 0, 1, 2, 3
print(my_query['MAST']['spectrum'][table]['data'][0])

13
[-3.7661755  4.63211   75.26402   ... 15.336566  11.698571  -4.98021  ]


In [7]:
my_query = myHermesBox.startQuery()
print(len(my_query))
print(my_query.keys())

for query in my_query:
    print('-------------------------------------------------------------------\n')
    print(my_query[query])

{'OAC': <Services.OAC.QueryOAC object at 0x7f34411c9ca0>, 'MAST': <Services.MAST.QueryMAST object at 0x7f34411c9670>, 'IRSA': <Services.IRSA.QueryIRSA object at 0x7f34411c9d30>, 'SIMBAD': <Services.SIMBAD.QuerySIMBAD object at 0x7f34411c9d60>}
OAC
Start query OAC
MAST
IRSA
Start query IRSA
SIMBAD
2
dict_keys(['OAC', 'IRSA'])
-------------------------------------------------------------------

 event    time  magnitude e_magnitude band instrument
------- ------- --------- ----------- ---- ----------
SN2021J 59228.5      12.5                            
-------------------------------------------------------------------

     obsmjd      mag_autocorr magerr_auto      oid            ra     ...  flags   photcalflag   goodflag    pid   
      days           mag          mag                      degrees   ...          0=No, 1=Yes 0=No, 1=Yes         
---------------- ------------ ----------- -------------- ----------- ... -------- ----------- ----------- --------
 56385.229587200        9.93

In [12]:
myHermesBox.generateVisualization()


KeyError: 'SIMBAD'

In [8]:
myHermes.generateVisualization()


Box(children=(Aladin(fov=0.2, layout=Layout(width='50%'), options=['allow_full_zoomout', 'coo_frame', 'fov', '…

In [9]:
myHermes.saveHermes()


{'search_type': {'type': 'cone_search', 'radius': 10.0}, 'ra/dec': ['12:26:27.011', '+31:13:20.55']}


In [10]:
aux=Hermes()
aux.loadHermes("save.Hermes")
aux.getFilters()

{'search_type': {'type': 'cone_search', 'radius': 10.0},
 'ra/dec': ['12:26:27.011', '+31:13:20.55']}

In [11]:
my_query_ = aux.startQuery()


{'OAC': <Services.OAC.QueryOAC object at 0x7f3465275580>, 'MAST': <Services.MAST.QueryMAST object at 0x7f34652750a0>, 'IRSA': <Services.IRSA.QueryIRSA object at 0x7f3474636280>, 'SIMBAD': <Services.SIMBAD.QuerySIMBAD object at 0x7f3474636580>}
OAC
Start query OAC
MAST
Start query MAST
IRSA
Start query IRSA
SIMBAD
Start query SIMBAD
